[project]
name = "fastsearch"
version = "0.1.0"
description = "Add a short description here"
authors = ["Dante Secada-Oz <me@danteoz.com>"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64"]

[tasks]

[dependencies]
python = "3.10.*"

[pypi-dependencies]
poetry = "*"
