[project]
name = "infra"
version = "0.1.0"
dependencies = [
    "aws-cdk-lib>=2.135.0",
    "aws-cdk-aws-apprunner-alpha>=2.135.0a0",
]
requires-python = ">= 3.12"

[tool.rye]
managed = true
virtual = true
dev-dependencies = []

[tool.ruff]
line-length = 110
