name: "Deploy"
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - "main"
  #   paths:
  #     - ".github/**"
  #     - "backend/**"
  #     - "infra/**"
  #     - "frontend/**"
  #     - "pipeline/**"

jobs:
  deploy-pipeline:
    name: Deploy Pipeline
    runs-on: ubuntu-latest
    env:
      MODAL_TOKEN_ID: ${{ secrets.MODAL_TOKEN_ID }}
      MODAL_TOKEN_SECRET: ${{ secrets.MODAL_TOKEN_SECRET }}
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v4
        with:
          version: "0.5.6"

      - name: Deploy job
        working-directory: pipeline/
        run: |
          uv run modal deploy modal/transcribe.py

  deploy-app:
    name: Deploy App
    runs-on: ubuntu-latest
    env:
      CERTIFICATE_ARN: ${{secrets.CERTIFICATE_ARN}}
      CDK_DEFAULT_ACCOUNT: ${{secrets.CDK_DEFAULT_ACCOUNT}}
      CDK_DEFAULT_REGION: ${{secrets.CDK_DEFAULT_REGION}}
      QDRANT_HOST: ${{secrets.QDRANT_HOST}}
      QDRANT_API_KEY: ${{secrets.QDRANT_API_KEY}}
      QDRANT_COLLECTION: ${{secrets.QDRANT_COLLECTION}}
      NUM_CANDIDATES: ${{secrets.NUM_CANDIDATES}}
      NUM_RESULTS: ${{secrets.NUM_RESULTS}}
      HF_TOKEN: ${{secrets.HF_TOKEN}}
      RETRIEVER_MODEL: ${{secrets.RETRIEVER_MODEL}}
      RANKING_MODEL: ${{secrets.RANKING_MODEL}}
      PGHOST: ${{secrets.PGHOST}}
      PGDATABASE: ${{secrets.PGDATABASE}}
      PGUSER: ${{secrets.PGUSER}}
      PGPASSWORD: ${{secrets.PGPASSWORD}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: 20.17.0
          # TODO: use node version file
      - uses: astral-sh/setup-uv@v4
        with:
          version: "0.5.6"

      - name: Build frontend
        working-directory: frontend/
        run: |
          npm install
          npm run build

      - name: Install infra (npm) dependencies
        working-directory: infra/
        run: npm i

      - name: Synth CDK Template
        working-directory: infra/
        run: npx cdk synth > /dev/null

      - name: Deploy CDK template
        working-directory: infra/
        run: npx cdk deploy > /dev/null
