name: "Update weights"
on:
  repository_dispatch:
    types:
      - update_weight

jobs:
  backfill:
    name: Deploy App
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .github
    steps:
      - name: Checkout release
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' 
          cache: 'pip' 
      
      - name: Install Python Dependencies
        run: |
          pip install --upgrade pip 
          pip install poetry
          poetry install -C backfill/
        
      - name: Backfill Indexing Pipeline
        env:
          SSH_HOST: ${{secrets.SSH_HOST}}
          SSH_PORT: ${{secrets.SSH_PORT}}
          SSH_USER: ${{secrets.SSH_USER}}
          SSH_KEY: ${{secrets.SSH_KEY}}
          DAGSTER_PORT: ${{secrets.DAGSTER_PORT}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          poetry run launch_backfill.py -C backfill/
        
      - name: Deploy Backend
        run: gh workflow run deploy.yaml

      
    