name: "Update weights"
on:
  repository_dispatch:
    types:
      - update_weight

jobs:
  backfill:
    name: Deploy App
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .github
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v4
        with:
          version: "0.5.6"

      - name: Backfill Indexing Pipeline
        env:
          SSH_HOST: ${{secrets.SSH_HOST}}
          SSH_PORT: ${{secrets.SSH_PORT}}
          SSH_USER: ${{secrets.SSH_USER}}
          SSH_KEY: ${{secrets.SSH_KEY}}
          DAGSTER_PORT: ${{secrets.DAGSTER_PORT}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: .github/backfill/launch_backfill.py
        run: |
          uv run launch_backfill.py

      - name: Deploy Backend
        run: gh workflow run deploy.yaml
